version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data
